# Generated by Django 4.0.2 on 2022-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registeration',
            field=models.CharField(choices=[('ISB', 'Islamabad'), ('RWP', 'Rawalpindi'), ('GJR', 'Gujranwala'), ('KHI', 'Karachi'), ('FSD', 'Faisalabad'), ('LHE', 'Lahore')], max_length=100),
        ),
    ]
