# Generated by Django 4.0.2 on 2022-02-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Kia', 'Kia'), ('Dahaitsu', 'Dahaitsu')], default='Honda', max_length=200),
        ),
    ]
